rdoc:
  title   : LibXML-Ruby
  main    : README
  include : [ ext, README, LICENSE ]

rubyforge:
  project  : libxml

release:
  package   : Stable Releases
  name      : libxml-ruby
  notelog   : NOTES
  changelog : ChangeLog

