---
title       : LibXML-Ruby
summary     : Ruby Bindings for GNU/LibXML2
description :
  LibXML-Ruby provides bindings to the GNU LibXML2 library.
homepage    : "http://libxml.rubyforge.org"
repository  : "http://libxml.rubyforge.org/svn/"
contact     : Dan Janwoski <danj at 3skel.com>
authors:
  - Dan Janwoski
  - Ross Bamform
  - Sean Chittenden
creator     : Sean Chittenden
created     : "2004-12-28"

# Packaging Information

package    : libxml-ruby

extensions :
  - ext/libxml/extconf.rb

gem_path:
  - ext

