---

index.html:
  main: layouts/normal.rhtml
  body: pages/index.red

install.html:
  main: layouts/normal.rhtml
  body: pages/install.red

license.html:
  main: layouts/normal.rhtml
  body: pages/license.html

images: images **/*

styles: styles **/*

